.travis.yml
test

Travis always builds for pull requests, other than that, we only need builds for work on travis itself, or on master, for checking the release code and maybe releasing versions.
Please note that builds currently fail due to 2 errors on windows. These should be fixed in a separate fix/ branch. I will force merge after successful review.

Setup Travis CI

---

api/config.go
config/persistence.go
config/persistence_test.go
config/perspective.go
database/controllers.go
database/database_test.go
database/dbmodule/maintenance.go
database/maintenance.go
modules/events.go
modules/tasks.go
modules/tasks_test.go
rng/rng.go
rng/test/.gitignore
rng/test/README.md
rng/test/main.go
test
utils/osdetail/version_windows.go

This a smorgasbord (🤣 what a word!) of commits - please review them separately.

Pre alpha finalizing

---

run/main.go

The stack is now also printed when there is an error during startup

Improve -print-stack-on-exit

---

api/config.go
config/database.go
config/expertise.go
config/get.go
config/get_test.go
config/option.go
config/perspective.go
config/registry.go
config/release.go
config/validate.go
modules/subsystems/module.go
modules/subsystems/subsystem.go
modules/subsystems/subsystems.go
template/module.go

Extends the config option system with new properties. Also adds a bit more type safety.

Extend config options

---

notifications/database.go
notifications/notification.go

This path drops support for persistent notifications as
they were always broken and not used anyway (see #71). As
a result, the locking strategy of the injected notification
backend has been updated and should improve database push
updates (i.e. the "upd" is now correct and no additional "new"
updates with partial data will be sent anymore)

Drop support for peristent notifications. Fixes #71

---

notifications/cleaner.go
notifications/database.go
notifications/notification.go

Based on #74, this PR further refactors the current notification system.
@dhaavi please review but do not yet merge!

Notification system refactoring

---

config/database.go
database/controller.go
database/controllers.go
database/database.go
database/database_test.go
database/registry.go
database/storage/badger/badger_test.go
database/storage/bbolt/bbolt.go
database/storage/bbolt/bbolt_test.go
database/storage/fstree/fstree.go
database/storage/fstree/fstree_test.go
database/storage/hashmap/map.go
database/storage/hashmap/map_test.go
database/storage/injectbase.go
database/storage/interface.go
notifications/database.go

Also, Move maintenance to separate interface.

Make shadow deletes conditional

---

database/controller.go
database/interface.go
database/storage/bbolt/bbolt.go
database/storage/bbolt/bbolt_test.go
database/storage/interface.go

Also, implement Purger interface in bbolt storage.

Add Purge method/interface to database system

---

api/config.go
config/expertise.go
config/option.go
config/perspective.go
config/release.go
config/validate.go
database/hook.go
modules/subsystems/module.go
modules/subsystems/registry.go
modules/subsystems/subsystem.go
notifications/cleaner.go
notifications/database.go
notifications/notification.go
runtime/module_api.go
runtime/registry.go
runtime/registry_test.go
template/module.go

Please view each commit separately.

Improvements for changes for new UI

---

config/option.go
notifications/notification.go

Also, improve on the notification handling a bit

Add Title and Category fields to Notification

---

utils/osdetail/binmeta.go
utils/osdetail/binmeta_default.go
utils/osdetail/binmeta_test.go
utils/osdetail/binmeta_windows.go
utils/osdetail/errors.go
utils/osdetail/powershell_windows.go
utils/osdetail/test/main_windows.go

Also, add generic binary name generator

Add binary metadata getters for windows

---

utils/osdetail/binmeta.go
utils/osdetail/binmeta_test.go
utils/osdetail/binmeta_windows.go
utils/osdetail/test/main_windows.go

Make it cleaner and improve resilience to errors.

Fix binary name getter on Windows

---

api/endpoints_debug.go
utils/debug/debug.go
utils/osdetail/binmeta.go
utils/osdetail/binmeta_test.go
utils/osdetail/powershell_windows.go

Also:
- Improve name cleaner
- Move debug util to separate pkg to avoid import loop

Set Powershell encoding to UTF-8

---

updater/storage.go
updater/updating.go

Improve empty index support

---

api/authentication.go
api/endpoints.go
container/container.go
container/container_test.go
database/interface.go
formats/dsd/dsd.go
formats/varint/helpers.go
formats/varint/varint.go
modules/microtasks.go
modules/modules.go
modules/tasks.go
modules/worker.go
utils/safe.go
utils/safe_test.go

And some other small things.
Would recommend to review commits individually.

Container and modules improvements

---

api/database.go
api/endpoints_modules.go
config/expertise.go
updater/updating.go

- Fix database api serialization warnings
- Fix api endpoint description
- Update expertise level option names
- Improve logging of updated update indexes

Minor fixes #3

---

api/endpoints.go
formats/dsd/dsd.go
formats/dsd/dsd_test.go
go.mod
go.sum
modules/error.go
modules/start.go
modules/stop.go
utils/debug/debug.go

- Add missing newlines to api ActionFunc messages
- Add dsd CBOR support
- Report module mgmt errors as module error messages
- Add module name to module error

Improve error handling

---

database/record/wrapper.go
go.mod
go.sum

- Update deps
- Fix wrapper dsd format

Fix wrapper dsd format

---

config/option.go
config/set.go

Fixes https://github.com/safing/portmaster-ui/issues/192.

Annotate config option if changed and restart is required

---

api/endpoints_debug.go
metrics/config.go
metrics/metrics_info.go

- Add go profiling debug api endpoints
- Add metrics comment for some additional info

Go profiling APIs and metrics comment

---

config/option.go
modules/tasks.go

- Add file-picker display hint
- Add options to disable task repeating and schedule

Add file-picker display hint and options for stopping task scheduling

---

.golangci.yml
api/authentication.go
container/container.go
container/container_test.go
modules/microtasks.go
modules/microtasks_test.go
modules/start.go

- Add microtask queues and signaling
- Remove deprecated code
- Expose container.Gather
- Update golangci-lint config
- Fix microtask signaling and improve tests
- Use new microtask function in api module

Improve microtasks with queues and signaling

---

.github/workflows/go.yml
.golangci.yml
api/database.go
api/endpoints_debug.go
api/router.go
modules/mgmt.go
run/main.go

- Update golang-ci and go workflow
- Fix linter errors
- Improve profiling API endpoint docs
- Add option to disable module management
- Improve exit code handling in run package

Small fixes and improvements

---

updater/resource.go
utils/osdetail/binmeta_test.go
utils/osdetail/svchost_windows.go

- Delete signature file when deleting resource
- Improve svchost service discovery
- Add name generation test case

Improve: delete sigs, binary metadata, svchost service detection

---

api/endpoints.go
api/endpoints_modules.go
log/input.go
log/logging.go
modules/export.go
modules/microtasks.go
modules/start.go

- Fix api endpoint log message
- Add module status export func and api endpoint
- Set default microtask threshold in init for easier override
- Improve logging control flow

Microtasks Improvements and Module Status Export

---

api/endpoints.go
api/endpoints_debug.go
api/request.go
metrics/api.go
metrics/metric.go
metrics/metric_counter.go
metrics/metric_counter_fetching.go
metrics/metric_export.go
metrics/metric_gauge.go
metrics/module.go

- Add internal ID to metric
- Export metrics with values and also export values only
- Add response headers to APIRequest
- Improve go profiling APIs

Improve Metrics and API

---

apprise/notify.go
metrics/metrics_host.go

- Add apprise convenience wrapper
- Fix comment

Add apprise convenience lib

---

database/record/base.go
metrics/api.go
metrics/module.go

- Add method to reset key of record
- Wait for metrics pusher before persisting metrics

Fix metrics race condition and add key reset method

---

updater/registry.go
updater/resource.go
updater/resource_test.go
updater/updating.go

- Exclude files that cannot be downloaded from version selection
- Improve method naming and update status data

Fix version selection
